# 5.NORMALIZE THE X VALUES(PRODUCED BY MULTIVARIATE REGRESSION)

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Import the file produced via, regression
lr_x=pd.read_csv('Updated_LR_Nutritional_Content.csv')

In [3]:
lr_x=lr_x.drop(['Unique_Ingredients'],axis=1)

In [4]:
lr_x.head()

sugars        fat    protein       sodium
0   5.317356  -1.724907  15.075557 -1553.711968
1 -11.634599  12.200291   6.893453   416.373060
2 -16.295311 -24.116738 -22.425870  -795.365939
3   8.188220  13.358360   1.661408   336.985633
4  -8.821069   2.058377  -3.561740   -42.563335

In [5]:
lr_x=lr_x.to_numpy()

In [6]:
R=np.load('out.npy')

In [7]:
print(R)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
#As negative values in x dont make any value, make then to 0
lr_x = np.where(lr_x<0,0,lr_x)

In [17]:
print(lr_x)

[[5.31735554e+00 0.00000000e+00 1.50755566e+01 0.00000000e+00]
 [0.00000000e+00 1.22002908e+01 6.89345274e+00 4.16373060e+02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 3.76000000e+12]
 [0.00000000e+00 7.79700464e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02420540e+01 0.00000000e+00 4.48055908e+02]]


In [21]:
#Find the maximum value in each nutrient coloumn
lr_x = np.where(lr_x<0,0,lr_x)
x1_max = np.amax(lr_x,axis=0)
print(x1_max)

[2.80e+14 3.04e+14 4.25e+14 1.59e+16]


In [24]:
#Set limit for each Nutrient, any value greater than this must be normalized
#Note that values for sodium are in mg, thus nesessary conversion has been done while setting the value
limit=[100,100,100,5000]

In [26]:
for j in range(4):
    for i in range(15662):
        if lr_x[i][j]>=limit[j]:
            lr_x[i][j]/=x1_max[j]
    

In [27]:
print(lr_x)

[[5.31735554e+00 0.00000000e+00 1.50755566e+01 0.00000000e+00]
 [0.00000000e+00 1.22002908e+01 6.89345274e+00 4.16373060e+02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.36477987e-04]
 [0.00000000e+00 7.79700464e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.02420540e+01 0.00000000e+00 4.48055908e+02]]


In [28]:
import pandas as pd
import numpy as np
df = pd.DataFrame(lr_x, columns = ['sugars','fat','protein','sodium'])

In [29]:
df.to_csv('Normalized_LR_Nutritional_content.csv')